In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = RandomForestClassifier(random_state=0)

In [ ]:
X = [[ 1,  2,  3],  # 2 samples, 3 features
     [11, 12, 13]]
y = [0, 1]  # classes of each sample


In [ ]:
clf.fit(X, y)


In [ ]:
# 1
# create a test set: X_test
# make predictions on X_test
X_test = [[3,4,5],[61,97,8]]
clf.predict(X_test)

In [ ]:
# 2
# Find code to replace randomforest with logistic regression and repeat the process
from sklearn.linear_model import LogisticRegression

In [ ]:
clf = LogisticRegression()
clf.fit(X,y)

In [ ]:
clf.predict(X_test)

In [55]:
# 3
# Read florence using pandas, and apply logistic regression on it
# Use whatever input variables you like
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV

In [32]:
df = pd.read_csv("florence.csv")

In [33]:
X = df.iloc[:,1:10].values

In [34]:
Y = df["Florence"]

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33)

In [53]:
#clf = DecisionTreeClassifier(random_state=0)
clf = RandomForestClassifier()

In [51]:
scoring = ['precision_macro', 'recall_macro',"roc_auc"]
scores = cross_val_score(clf, X_train, y_train, cv=10,scoring="roc_auc")
scores

array([0.6956044 , 0.74945055, 0.64774115, 0.65689866, 0.6996337 ,
       0.65811966, 0.61172161, 0.73382173, 0.62454212, 0.78327228])

In [52]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.69 (+/- 0.11)


In [64]:
# gridsearch

param_grid = [
  {'n_estimators': [100,150,200], 'criterion': ['gini','entropy'],'max_depth':[5,15,20]}
 ]
gc=GridSearchCV(clf, param_grid, cv=5)

In [65]:
gc.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [66]:
gc.best_params_

{'criterion': 'gini', 'max_depth': 5, 'n_estimators': 100}

In [69]:
clf = RandomForestClassifier(criterion='gini', max_depth= 5, n_estimators= 100)

In [70]:
scores = cross_val_score(clf, X_train, y_train, cv=10,scoring="roc_auc")
scores

array([0.75604396, 0.78131868, 0.67277167, 0.67765568, 0.72283272,
       0.64835165, 0.71916972, 0.7032967 , 0.63003663, 0.82417582])

In [71]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.71 (+/- 0.11)


In [73]:
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [74]:
dt_pred = clf.predict(X_test)

In [85]:
dt_pred_prob = clf.predict_proba(X_test)
flor_pred =[x[1] for x in dt_pred_prob]

In [75]:
clf.score(X_test,y_test)

0.9191919191919192

In [77]:
from sklearn import metrics

In [ ]:
print(metrics.classification_report(y_test,dt_pred))

In [79]:
metrics.confusion_matrix(y_test,dt_pred)

array([[455,   0],
       [ 40,   0]])

In [86]:
metrics.roc_auc_score(y_test,flor_pred)

0.704835164835165

In [ ]:
from sklearn.preprocessing import StandardScaler
X = [[0.0, 150.0,0.0,10.0],
     [1.0, -10.0,2000.0,2.0],
     [1.0, -10.0,0.0,2.0],
     [1.0, -100.0,0.0,2.0]]
X_scale = StandardScaler().fit(X).transform(X)

In [ ]:
X_scale

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
enc = OneHotEncoder()

In [ ]:
enc_out = enc.fit(df.loc[:,"ArtBks"].values.reshape(-1, 1)).transform(df.loc[:,"ArtBks"].values.reshape(-1, 1))

In [ ]:
enc_out.toarray()

In [ ]:
 from sklearn import preprocessing
binn = preprocessing.Binarizer(threshold=3)

In [ ]:
binn.fit(df.loc[:,"ArtBks"].values.reshape(-1, 1)).transform(df.loc[:,"ArtBks"].values.reshape(-1, 1))

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp.fit([[1, 6], [np.nan, 3], [7, 6]])

X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(imp.transform(X))

In [ ]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, random_state=0)
imp.fit([[1, 2], [3, 6], [4, 8], [np.nan, 3], [7, np.nan]])

X_test = [[np.nan, 2], [6, np.nan], [np.nan, 6]]
# the model learns that the second feature is double the first
print(np.round(imp.transform(X_test)))

In [ ]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)
X


In [ ]:
poly = PolynomialFeatures(2)
poly.fit_transform(X)